# Generated by Django 3.2 on 2021-09-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedidoInsightItens',
            new_name='ItemPedidoInsight',
        ),
    ]
