# Generated by Django 3.1.7 on 2021-07-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='sugestao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
