# Generated by Django 3.1.7 on 2021-11-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='preco_venda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
