# Generated by Django 3.1.7 on 2021-07-22 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerta',
            old_name='desc_filial',
            new_name='valor',
        ),
        migrations.AddField(
            model_name='alerta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='estoque',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='qt_excesso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='sugestao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='vl_excesso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='principio_ativo',
            field=models.BooleanField(default=False, verbose_name='Considerar Princípio Ativo'),
        ),
        migrations.CreateModel(
            name='GraficoRuptura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curva', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grafruptura_empresa', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='GraficoCurva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curva', models.CharField(blank=True, max_length=255, null=True)),
                ('normal', models.FloatField(blank=True, null=True)),
                ('parcial', models.FloatField(blank=True, null=True)),
                ('excesso', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grafcurva_empresa', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_empresa', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DadosEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curva', models.CharField(blank=True, max_length=255, null=True)),
                ('skus', models.IntegerField(blank=True, null=True)),
                ('normal', models.IntegerField(blank=True, null=True)),
                ('parcial', models.IntegerField(blank=True, null=True)),
                ('ruptura', models.IntegerField(blank=True, null=True)),
                ('excesso', models.IntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dadosestoque_empresa', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Dados Estoque',
                'verbose_name_plural': 'Dados Estoque',
            },
        ),
    ]
