# Generated by Django 3.1.7 on 2021-04-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_academy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
