# Generated by Django 3.1.7 on 2021-07-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210719_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='qt_excesso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='vl_excesso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
