# Generated by Django 3.1.7 on 2021-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210714_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='estoque',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
