# Generated by Django 3.1.7 on 2021-07-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210722_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graficocurva',
            name='excesso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='graficocurva',
            name='normal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='graficocurva',
            name='parcial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='graficocurva',
            name='total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
