# Generated by Django 3.1.7 on 2021-07-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alerta_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='valor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
