# Generated by Django 3.1.7 on 2021-04-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210420_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
