# Generated by Django 3.1.7 on 2021-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210721_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='desc_filial',
        ),
        migrations.AddField(
            model_name='empresa',
            name='principio_ativo',
            field=models.BooleanField(default=True, verbose_name='Considerar Princípio Ativo'),
        ),
    ]
