# Generated by Django 3.1.7 on 2021-03-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210325_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='bairro',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
