# Generated by Django 3.1.7 on 2021-07-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210722_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='principio_ativo',
            field=models.BooleanField(default=False, verbose_name='Considerar Princípio Ativo'),
        ),
    ]
