# Generated by Django 3.1.7 on 2021-05-14 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_academy_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_filial', models.IntegerField(blank=True)),
                ('desc_filial', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filial_empresa', to='core.empresa')),
            ],
        ),
    ]
