# Generated by Django 3.1.7 on 2021-07-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
