# Generated by Django 3.1.7 on 2021-05-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_filial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Filial', 'verbose_name_plural': 'Filiais'},
        ),
    ]
