# Generated by Django 3.1.7 on 2021-07-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alerta_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curva', models.CharField(blank=True, max_length=255, null=True)),
                ('skus', models.IntegerField(blank=True, null=True)),
                ('normal', models.IntegerField(blank=True, null=True)),
                ('parcial', models.IntegerField(blank=True, null=True)),
                ('excesso', models.IntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dadosestoque_empresa', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Dados Estoque',
                'verbose_name_plural': 'Dados Estoque',
            },
        ),
    ]
