# Generated by Django 3.1.7 on 2021-04-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210406_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissao',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='usuario',
        ),
    ]
