# Generated by Django 3.1.7 on 2021-04-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210406_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissao',
            options={'verbose_name': 'Permissão', 'verbose_name_plural': 'Permissões'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='permissao',
        ),
    ]
