# Generated by Django 3.1.7 on 2021-07-19 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dadosestoque_ruptura'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraficoRuptura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curva', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grafruptura_empresa', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='GraficoCurva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curva', models.CharField(blank=True, max_length=255, null=True)),
                ('normal', models.FloatField(blank=True, null=True)),
                ('parcial', models.FloatField(blank=True, null=True)),
                ('excesso', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grafcurva_empresa', to='core.empresa')),
            ],
        ),
    ]
