# Generated by Django 3.1.7 on 2021-04-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210406_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Permissao',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
