# Generated by Django 3.1.7 on 2021-04-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210413_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
