# Generated by Django 3.1.7 on 2021-04-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210413_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='iestadual',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
