# Generated by Django 3.1.7 on 2021-04-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_empresa_iestadual'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
