# Generated by Django 3.1.7 on 2021-07-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('desc_fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('leadtime', models.IntegerField(blank=True, null=True)),
                ('ciclo_reposicao', models.IntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fonecedor_empresa', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedor',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('embalagem', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade_un_cx', models.FloatField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('peso_liq', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='core.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_produto', to='api.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('qt_vendas', models.IntegerField(blank=True, null=True)),
                ('qt_unit_caixa', models.IntegerField(blank=True, null=True)),
                ('preco_unit', models.FloatField(blank=True, null=True)),
                ('custo_fin', models.FloatField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('peso_liquido', models.FloatField(blank=True, null=True)),
                ('cod_depto', models.IntegerField(blank=True, null=True)),
                ('num_nota', models.IntegerField(blank=True, null=True)),
                ('cod_usur', models.IntegerField(blank=True, null=True)),
                ('cod_fab', models.IntegerField(blank=True, null=True)),
                ('desc_dois', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_venda', to='core.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filial_venda', to='core.filial')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_venda', to='api.fornecedor')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_venda', to='api.produto')),
            ],
        ),
        migrations.CreateModel(
            name='UltimaEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('qt_ult_entrada', models.IntegerField(blank=True, null=True)),
                ('vl_ult_entrada', models.FloatField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_ultimaentrada', to='core.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filial_ultimaentrada', to='core.filial')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_ultimaentrada', to='api.fornecedor')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_ultimaentrada', to='api.produto')),
            ],
            options={
                'verbose_name': 'Ultima entrada',
                'verbose_name_plural': 'Ultimas entradas',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('saldo', models.IntegerField(blank=True, null=True)),
                ('num_pedido', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_pedidos', to='core.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filial_pedidos', to='core.filial')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_pedidos', to='api.fornecedor')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_pedidos', to='api.produto')),
            ],
            options={
                'verbose_name': 'Pedido de compra',
                'verbose_name_plural': 'Pedidos de compra',
            },
        ),
        migrations.CreateModel(
            name='HistoricoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('embalagem', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('qt_estoque', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_historicoestoque', to='core.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filial_historicoestoque', to='core.filial')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_historicoestoque', to='api.fornecedor')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_historicoestoque', to='api.produto')),
            ],
            options={
                'verbose_name': 'Histórico de estoque',
                'verbose_name_plural': 'Históricos de estoque',
            },
        ),
        migrations.CreateModel(
            name='EstoqueAtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('embalagem', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('qt_estoque_geral', models.IntegerField(blank=True, null=True)),
                ('qt_indenizada', models.IntegerField(blank=True, null=True)),
                ('qt_reservada', models.IntegerField(blank=True, null=True)),
                ('qt_pendente', models.IntegerField(blank=True, null=True)),
                ('qt_bloqueada', models.IntegerField(blank=True, null=True)),
                ('qt_disponivel', models.IntegerField(blank=True, null=True)),
                ('custo_ult_ent', models.FloatField(blank=True, null=True)),
                ('preco_venda', models.FloatField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_estoqueatual', to='core.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filial_estoqueatual', to='core.filial')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_estoqueatual', to='api.fornecedor')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_estoqueatual', to='api.produto')),
            ],
            options={
                'verbose_name': 'Estoque atual',
                'verbose_name_plural': 'Estoque atual',
            },
        ),
    ]
