# Generated by Django 3.1.7 on 2021-05-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('desc_fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fonecedor_empresa', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedor',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('embalagem', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade_un_cx', models.IntegerField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('peso_liq', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='core.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_produto', to='api.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('qt_vendas', models.IntegerField(blank=True, null=True)),
                ('preco_unit', models.FloatField(blank=True, null=True)),
                ('custo_fin', models.FloatField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_vendas', to='core.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_vendas', to='api.fornecedor')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_vendas', to='api.produto')),
            ],
        ),
        migrations.CreateModel(
            name='UltimaEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('qt_ult_entrada', models.IntegerField(blank=True, null=True)),
                ('vl_ult_entrada', models.FloatField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_ultentrada', to='core.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_ultentrada', to='api.fornecedor')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_ultentrada', to='api.produto')),
            ],
            options={
                'verbose_name': 'Ultima entrada',
                'verbose_name_plural': 'Ultimas entradas',
            },
        ),
        migrations.CreateModel(
            name='PedidoCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('saldo', models.IntegerField(blank=True, null=True)),
                ('num_pedido', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_pcompras', to='core.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_pcompras', to='api.fornecedor')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_pcompras', to='api.produto')),
            ],
            options={
                'verbose_name': 'Pedido de compra',
                'verbose_name_plural': 'Pedidos de compra',
            },
        ),
        migrations.CreateModel(
            name='HistEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('qt_estoque', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_histestoque', to='core.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_histestoque', to='api.fornecedor')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_histestoque', to='api.produto')),
            ],
            options={
                'verbose_name': 'Histórico de estoque',
                'verbose_name_plural': 'Históricos de estoque',
            },
        ),
        migrations.CreateModel(
            name='EstoqueAtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('qt_estoque_geral', models.IntegerField(blank=True, null=True)),
                ('qt_indenizada', models.IntegerField(blank=True, null=True)),
                ('qt_reservada', models.IntegerField(blank=True, null=True)),
                ('qt_pendente', models.IntegerField(blank=True, null=True)),
                ('qt_disponivel', models.IntegerField(blank=True, null=True)),
                ('custo_ult_ent', models.FloatField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_estoqueatual', to='core.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_estoqueatual', to='api.fornecedor')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_estoqueatual', to='api.produto')),
            ],
            options={
                'verbose_name': 'Estoque atual',
                'verbose_name_plural': 'Estoque atual',
            },
        ),
        migrations.CreateModel(
            name='Avaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('qt_avaria', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_avarias', to='core.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_avarias', to='api.fornecedor')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_avarias', to='api.produto')),
            ],
        ),
    ]
