# Generated by Django 3.1.7 on 2021-05-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaria',
            old_name='cod_fornec',
            new_name='cod_fornecedor',
        ),
        migrations.RenameField(
            model_name='estoqueatual',
            old_name='cod_fornec',
            new_name='cod_fornecedor',
        ),
        migrations.RenameField(
            model_name='histestoque',
            old_name='cod_fornec',
            new_name='cod_fornecedor',
        ),
        migrations.RenameField(
            model_name='pedidocompras',
            old_name='cod_fornec',
            new_name='cod_fornecedor',
        ),
        migrations.RenameField(
            model_name='ultimaentrada',
            old_name='cod_fornec',
            new_name='cod_fornecedor',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='cod_fornec',
            new_name='cod_fornecedor',
        ),
    ]
