# Generated by Django 3.1.7 on 2021-08-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='qt_bloqueada',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='qt_disponivel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='qt_geral',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='qt_indenizada',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='qt_pendente',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='qt_reservada',
            field=models.FloatField(),
        ),
    ]
