# Generated by Django 3.1.7 on 2021-05-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='qt_unit_caixa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
