# Generated by Django 3.1.7 on 2021-03-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_compras', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='cod_filial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cod_fornec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='embalagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='produto',
            name='qt_avaria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='qt_venda',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
