# Generated by Django 3.1.7 on 2021-06-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueatual',
            name='embalagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estoqueatual',
            name='preco_venda',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estoqueatual',
            name='qt_bloqueada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='histestoque',
            name='embalagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='cod_depto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='cod_fab',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='cod_usur',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='desc_dois',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='num_nota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='peso_liquido',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='supervisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
