# Generated by Django 3.1.7 on 2021-07-22 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210722_1744'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('qt_ult_entrada', models.IntegerField(blank=True, null=True)),
                ('vl_ult_entrada', models.FloatField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_entrada', to='core.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filial_entrada', to='core.filial')),
            ],
            options={
                'verbose_name': 'Ultima entrada',
                'verbose_name_plural': 'Ultimas entradas',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('cod_filial', models.IntegerField(blank=True, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('qt_geral', models.IntegerField(blank=True, null=True)),
                ('qt_indenizada', models.IntegerField(blank=True, null=True)),
                ('qt_reservada', models.IntegerField(blank=True, null=True)),
                ('qt_pendente', models.IntegerField(blank=True, null=True)),
                ('qt_bloqueada', models.IntegerField(blank=True, null=True)),
                ('qt_disponivel', models.IntegerField(blank=True, null=True)),
                ('custo_ult_entrada', models.FloatField(blank=True, null=True)),
                ('preco_venda', models.FloatField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_estoqueatual', to='core.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filial_estoqueatual', to='core.filial')),
            ],
            options={
                'verbose_name': 'Estoque atual',
                'verbose_name_plural': 'Estoque atual',
            },
        ),
        migrations.RemoveField(
            model_name='ultimaentrada',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='ultimaentrada',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='ultimaentrada',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='ultimaentrada',
            name='produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='peso_liq',
            new_name='desc_departamento',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='cod_aux',
            new_name='qt_venda',
        ),
        migrations.RemoveField(
            model_name='historicoestoque',
            name='desc_produto',
        ),
        migrations.RemoveField(
            model_name='historicoestoque',
            name='embalagem',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='desc_produto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='cod_depto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='cod_fab',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='desc_dept',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='desc_produto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='peso_liquido',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='qt_unit_caixa',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='qt_vendas',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='secao',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='iestadual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='tempo_estoque',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cod_auxiliar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cod_depto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cod_fabrica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='desc_secao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_liquido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='principio_ativo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='EstoqueAtual',
        ),
        migrations.DeleteModel(
            name='UltimaEntrada',
        ),
        migrations.AddField(
            model_name='estoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_estoqueatual', to='api.fornecedor'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_estoqueatual', to='api.produto'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_entrada', to='api.fornecedor'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_entrada', to='api.produto'),
        ),
    ]
