# Generated by Django 3.1.7 on 2021-05-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueatual',
            name='custo_ult_ent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultimaentrada',
            name='vl_ult_entrada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='custo_fin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='preco_unit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
