# Generated by Django 3.1.7 on 2021-06-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210608_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade_un_cx',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
