# Generated by Django 3.1.7 on 2021-03-30 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario'),
        ('api', '0002_auto_20210330_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='core.empresa'),
        ),
    ]
