# Generated by Django 3.1.7 on 2021-07-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210722_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cod_ncm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
