# Generated by Django 3.1.7 on 2021-07-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210719_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='desc_produto',
        ),
    ]
