# Generated by Django 3.1.7 on 2021-05-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210518_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaria',
            name='desc_produto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
