# Generated by Django 3.1.7 on 2021-08-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('api', '0002_auto_20210809_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos_API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.IntegerField()),
                ('cod_filial', models.IntegerField()),
                ('cod_fornecedor', models.IntegerField()),
                ('saldo', models.IntegerField()),
                ('num_pedido', models.IntegerField()),
                ('data', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('campo_um', models.CharField(blank=True, max_length=255, null=True)),
                ('campo_dois', models.CharField(blank=True, max_length=255, null=True)),
                ('campo_tres', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_pedidosapi', to='core.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filial_pedidosapi', to='core.filial')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_pedidosapi', to='api.fornecedor')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_pedidosapi', to='api.produto')),
            ],
            options={
                'verbose_name': 'Pedido API',
                'verbose_name_plural': 'Pedidos API',
            },
        ),
    ]
