# Generated by Django 3.1.7 on 2021-07-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210722_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='cod_usur',
        ),
        migrations.AddField(
            model_name='venda',
            name='rca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
