# Generated by Django 3.1.7 on 2021-07-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210611_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='desc_dois',
            new_name='desc_dept',
        ),
        migrations.AddField(
            model_name='venda',
            name='secao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
