# Generated by Django 3.1.7 on 2021-05-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210511_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='qt_avaria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='qt_venda',
        ),
    ]
