# Generated by Django 3.1.7 on 2021-08-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pedidos_api'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos_api',
            options={'verbose_name': 'Pedido Existente', 'verbose_name_plural': 'Pedidos Existentes'},
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
