# Generated by Django 3.1.7 on 2021-07-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_venda_desc_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='custo_ult_entrada',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
