# Generated by Django 3.1.7 on 2021-05-14 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_filial'),
        ('api', '0004_auto_20210511_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filial_produto', to='core.filial'),
        ),
    ]
