# Generated by Django 3.1.7 on 2021-07-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210712_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cod_aux',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
