# Generated by Django 3.1.7 on 2021-07-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210720_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='preco_venda',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
