# Generated by Django 3.1.7 on 2021-07-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_venda_cod_aux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cod_aux',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
