# Generated by Django 3.1.7 on 2021-05-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_produto_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='filial',
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_liq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_un_cx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
