# Generated by Django 3.1.7 on 2021-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_estoque_preco_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='principio_ativo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
