# Generated by Django 3.1.7 on 2021-05-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210514_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parametro',
        ),
    ]
