version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: insigth-db
    environment:
      POSTGRES_DB: "web-insigth"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    container_name: insigth-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
